export type Project = {
  id: string;
  workspaceId: string;
  ownerUid: string;
  title: string;
  description: string;
  status: 'active' | 'completed' | 'paused' | 'archived';
  visibility: 'private' | 'workspace' | 'public';
  fieldOfStudy: string | null;
  projectType: string | null;
  keywords: string[];
  collaborators: string[];
  completionPct: number;
  deadline: string | null;
  documentCount: number;
  taskCount: number;
  completedTasks: number;
  metadata: Record<string, unknown>;
  createdAt: string;
  updatedAt: string;
  deletedAt: string | null;
};

export type ProjectDocument = {
  id: string;
  projectId: string;
  ownerUid: string;
  title: string;
  docType: 'document' | 'spreadsheet' | 'presentation' | 'note' | 'bibliography';
  content: string;
  contentJson: Record<string, unknown>;
  wordCount: number;
  charCount: number;
  pageCount: number;
  version: number;
  plagiarismScore: number | null;
  aiContentScore: number | null;
  readabilityScore: number | null;
  collaborators: string[];
  isPublic: boolean;
  status: 'active' | 'archived' | 'trashed';
  isTemplate: boolean;
  parentId: string | null;
  abstract: string | null;
  keywords: string[];
  citationStyle: string;
  language: string;
  metadata: Record<string, unknown>;
  createdAt: string;
  updatedAt: string;
  deletedAt: string | null;
};

export type ProjectSlide = {
  id: string;
  projectId: string;
  ownerUid: string;
  title: string;
  slideData: unknown[];
  slideCount: number;
  version: number;
  collaborators: string[];
  isPublic: boolean;
  status: string;
  isTemplate: boolean;
  metadata: Record<string, unknown>;
  createdAt: string;
  updatedAt: string;
  deletedAt: string | null;
};

export type ProjectNote = {
  id: string;
  projectId: string;
  ownerUid: string;
  title: string;
  content: string;
  contentJson: Record<string, unknown>;
  collaborators: string[];
  isPublic: boolean;
  status: string;
  metadata: Record<string, unknown>;
  createdAt: string;
  updatedAt: string;
  deletedAt: string | null;
};

export type ProjectTask = {
  id: string;
  projectId: string;
  documentId: string | null;
  slideId: string | null;
  noteId: string | null;
  ownerUid: string;
  assigneeUid: string | null;
  createdByUid: string;
  title: string;
  description: string;
  status: 'todo' | 'in_progress' | 'in_review' | 'done' | 'cancelled';
  priority: 'low' | 'medium' | 'high' | 'urgent';
  taskType: string;
  dueDate: string | null;
  startedAt: string | null;
  completedAt: string | null;
  estimatedHours: number | null;
  actualHours: number | null;
  tags: string[];
  attachments: unknown[];
  subtasks: unknown[];
  commentsCount: number;
  displayOrder: number;
  metadata: Record<string, unknown>;
  createdAt: string;
  updatedAt: string;
  deletedAt: string | null;
};
